# Generated by Django 5.2.17 on 2026-08-31 13:55

import datetime

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
        ("wealth", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PlusValueTaxRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("year", models.PositiveIntegerField(unique=True)),
                (
                    "rate_percent",
                    models.DecimalField(decimal_places=2, default=10, max_digits=5),
                ),
                (
                    "annual_exemption",
                    models.DecimalField(
                        decimal_places=2,
                        default=10000,
                        help_text="Exonération annuelle par contribuable (indexée chaque année).",
                        max_digits=10,
                    ),
                ),
                (
                    "reference_date",
                    models.DateField(
                        default=datetime.date(2025, 12, 31),
                        help_text="Date de référence pour la valeur de grandfathering des positions existantes.",
                    ),
                ),
            ],
            options={
                "verbose_name": "règle taxe plus-value",
                "verbose_name_plural": "règles taxe plus-value",
                "ordering": ["-year"],
            },
        ),
        migrations.CreateModel(
            name="PrecompteMobilierRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("year", models.PositiveIntegerField(unique=True)),
                (
                    "rate_percent",
                    models.DecimalField(decimal_places=2, default=30, max_digits=5),
                ),
                (
                    "savings_account_exempt_threshold",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Première tranche d'intérêts de compte d'épargne réglementé exonérée de précompte.",
                        max_digits=8,
                    ),
                ),
            ],
            options={
                "verbose_name": "règle précompte mobilier",
                "verbose_name_plural": "règles précompte mobilier",
                "ordering": ["-year"],
            },
        ),
        migrations.CreateModel(
            name="TOBRate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "instrument_type",
                    models.CharField(
                        choices=[
                            ("bonds", "Obligations"),
                            ("shares", "Actions / parts de distribution"),
                            ("capitalization", "Fonds de capitalisation"),
                        ],
                        max_length=20,
                        unique=True,
                    ),
                ),
                ("rate_percent", models.DecimalField(decimal_places=3, max_digits=5)),
                ("cap_amount", models.DecimalField(decimal_places=2, max_digits=8)),
                ("effective_from", models.DateField()),
            ],
            options={
                "verbose_name": "taux TOB",
                "verbose_name_plural": "taux TOB",
            },
        ),
        migrations.CreateModel(
            name="CapitalGainRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cost_basis", models.DecimalField(decimal_places=2, max_digits=14)),
                ("proceeds", models.DecimalField(decimal_places=2, max_digits=14)),
                ("realized_gain", models.DecimalField(decimal_places=2, max_digits=14)),
                ("tax_year", models.PositiveIntegerField()),
                ("computed_at", models.DateTimeField(auto_now=True)),
                (
                    "household",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="accounts.household",
                    ),
                ),
                (
                    "security_transaction",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="capital_gain",
                        to="wealth.securitytransaction",
                    ),
                ),
            ],
            options={
                "verbose_name": "plus-value réalisée",
                "verbose_name_plural": "plus-values réalisées",
                "ordering": ["-tax_year"],
            },
        ),
    ]
