# Generated by Django 5.2.17 on 2026-08-31 13:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import apps.imports_app.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
        ("budget", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ImportBatch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        upload_to=apps.imports_app.models.import_upload_path
                    ),
                ),
                ("column_mapping", models.JSONField(blank=True, default=dict)),
                ("date_format", models.CharField(default="%d/%m/%Y", max_length=20)),
                ("delimiter", models.CharField(default=",", max_length=1)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "En attente de mapping"),
                            ("mapped", "Mappé, en attente de confirmation"),
                            ("confirmed", "Importé"),
                            ("failed", "Échec"),
                        ],
                        default="pending",
                        max_length=10,
                    ),
                ),
                ("imported_count", models.PositiveIntegerField(default=0)),
                ("skipped_duplicate_count", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="import_batches",
                        to="budget.financialaccount",
                    ),
                ),
                (
                    "household",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="accounts.household",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "import CSV",
                "verbose_name_plural": "imports CSV",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ImportMappingTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="nom")),
                (
                    "column_mapping",
                    models.JSONField(
                        help_text="Association champ Kiwi -> nom de colonne du CSV."
                    ),
                ),
                ("date_format", models.CharField(default="%d/%m/%Y", max_length=20)),
                ("delimiter", models.CharField(default=",", max_length=1)),
                (
                    "household",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="accounts.household",
                    ),
                ),
            ],
            options={
                "verbose_name": "modèle de mapping d'import",
                "verbose_name_plural": "modèles de mapping d'import",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("household", "name"),
                        name="unique_template_per_household",
                    )
                ],
            },
        ),
    ]
