# Generated by Django 5.2.17 on 2026-08-31 13:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
        ("budget", "0001_initial"),
        ("fx", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Liability",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("mortgage", "Crédit hypothécaire"),
                            ("loan", "Prêt personnel"),
                            ("credit", "Crédit renouvelable"),
                        ],
                        max_length=20,
                        verbose_name="type",
                    ),
                ),
                ("name", models.CharField(max_length=150, verbose_name="nom")),
                (
                    "principal",
                    models.DecimalField(
                        decimal_places=2, max_digits=14, verbose_name="montant emprunté"
                    ),
                ),
                (
                    "remaining_balance",
                    models.DecimalField(
                        decimal_places=2, max_digits=14, verbose_name="solde restant dû"
                    ),
                ),
                (
                    "interest_rate",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        verbose_name="taux d'intérêt (%)",
                    ),
                ),
                (
                    "started_at",
                    models.DateField(
                        blank=True, null=True, verbose_name="date de départ"
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                (
                    "currency",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="fx.currency",
                    ),
                ),
                (
                    "household",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="accounts.household",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        help_text="Laisser vide pour un élément commun au foyer.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "dette",
                "verbose_name_plural": "dettes",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="RealAsset",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("real_estate", "Immobilier"),
                            ("vehicle", "Véhicule"),
                            ("other", "Autre"),
                        ],
                        max_length=20,
                        verbose_name="type",
                    ),
                ),
                ("name", models.CharField(max_length=150, verbose_name="nom")),
                (
                    "acquisition_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="date d'acquisition"
                    ),
                ),
                (
                    "acquisition_value",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=14,
                        verbose_name="valeur d'acquisition",
                    ),
                ),
                (
                    "current_value",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=14,
                        verbose_name="valeur actuelle estimée",
                    ),
                ),
                (
                    "current_value_updated_at",
                    models.DateField(
                        blank=True, null=True, verbose_name="valeur estimée au"
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                (
                    "currency",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="fx.currency",
                    ),
                ),
                (
                    "household",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="accounts.household",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        help_text="Laisser vide pour un élément commun au foyer.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "actif réel",
                "verbose_name_plural": "actifs réels",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Security",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "identifier",
                    models.CharField(
                        help_text="Ex: IE00B4L5Y983",
                        max_length=20,
                        unique=True,
                        verbose_name="ISIN / ticker",
                    ),
                ),
                ("name", models.CharField(max_length=150, verbose_name="nom")),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("stock", "Action"),
                            ("etf", "ETF"),
                            ("fund", "Fonds"),
                            ("bond", "Obligation"),
                            ("crypto", "Crypto-actif"),
                        ],
                        default="etf",
                        max_length=10,
                        verbose_name="type",
                    ),
                ),
                (
                    "currency",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="fx.currency",
                    ),
                ),
            ],
            options={
                "verbose_name": "valeur mobilière",
                "verbose_name_plural": "valeurs mobilières",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="SecurityTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(verbose_name="date")),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("buy", "Achat"),
                            ("sell", "Vente"),
                            ("dividend", "Dividende"),
                            ("fee", "Frais"),
                        ],
                        max_length=10,
                        verbose_name="type",
                    ),
                ),
                (
                    "quantity",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        max_digits=18,
                        null=True,
                        verbose_name="quantité",
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        max_digits=18,
                        null=True,
                        verbose_name="prix unitaire",
                    ),
                ),
                (
                    "fees",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=10, verbose_name="frais"
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Montant brut pour un dividende ou des frais.",
                        max_digits=14,
                        null=True,
                        verbose_name="montant",
                    ),
                ),
                ("notes", models.CharField(blank=True, max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="security_transactions",
                        to="budget.financialaccount",
                    ),
                ),
                (
                    "currency",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="fx.currency",
                    ),
                ),
                (
                    "household",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="accounts.household",
                    ),
                ),
                (
                    "security",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="transactions",
                        to="wealth.security",
                    ),
                ),
            ],
            options={
                "verbose_name": "opération sur titres",
                "verbose_name_plural": "opérations sur titres",
                "ordering": ["-date", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="NetWorthSnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("total_assets", models.DecimalField(decimal_places=2, max_digits=16)),
                (
                    "total_liabilities",
                    models.DecimalField(decimal_places=2, max_digits=16),
                ),
                ("net_worth", models.DecimalField(decimal_places=2, max_digits=16)),
                (
                    "breakdown",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Détail par propriétaire / classe d'actif.",
                    ),
                ),
                (
                    "household",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="accounts.household",
                    ),
                ),
            ],
            options={
                "verbose_name": "photo du patrimoine",
                "verbose_name_plural": "photos du patrimoine",
                "ordering": ["-date"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("household", "date"), name="unique_snapshot_per_day"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="PriceSnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("price", models.DecimalField(decimal_places=6, max_digits=18)),
                (
                    "security",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="prices",
                        to="wealth.security",
                    ),
                ),
            ],
            options={
                "verbose_name": "cours",
                "verbose_name_plural": "cours",
                "ordering": ["-date"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("security", "date"), name="unique_price_per_day"
                    )
                ],
            },
        ),
    ]
