# Generated by Django 5.2.17 on 2026-09-02 11:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wealth", "0002_alter_liability_owner_alter_realasset_owner"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="liability",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                help_text="Laisser vide pour un élément commun au foyer.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
                verbose_name="propriétaire",
            ),
        ),
        migrations.AlterField(
            model_name="realasset",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                help_text="Laisser vide pour un élément commun au foyer.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
                verbose_name="propriétaire",
            ),
        ),
    ]
