# Generated by Django 5.2.17 on 2026-09-02 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wealth", "0003_alter_liability_owner_alter_realasset_owner"),
    ]

    operations = [
        migrations.AddField(
            model_name="security",
            name="last_sync_error",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="dernière erreur de synchro"
            ),
        ),
        migrations.AddField(
            model_name="security",
            name="last_synced_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="dernière synchro"
            ),
        ),
        migrations.AddField(
            model_name="security",
            name="yahoo_symbol",
            field=models.CharField(
                blank=True,
                help_text="Ticker Yahoo, distinct de l'ISIN — Yahoo ne sait pas chercher par ISIN. Ex: IWDA.AS pour le listing d'Amsterdam. Laissez vide pour saisir les cours à la main.",
                max_length=30,
                verbose_name="symbole Yahoo Finance",
            ),
        ),
    ]
