# Generated by Django 5.2.17 on 2026-08-31 13:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Currency",
            fields=[
                (
                    "code",
                    models.CharField(max_length=3, primary_key=True, serialize=False),
                ),
                ("name", models.CharField(max_length=50)),
                ("symbol", models.CharField(blank=True, max_length=5)),
            ],
            options={
                "verbose_name": "devise",
                "verbose_name_plural": "devises",
                "ordering": ["code"],
            },
        ),
        migrations.CreateModel(
            name="ExchangeRate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                (
                    "rate",
                    models.DecimalField(
                        decimal_places=8,
                        help_text="1 base_currency = rate * quote_currency",
                        max_digits=18,
                    ),
                ),
                (
                    "base_currency",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rates_as_base",
                        to="fx.currency",
                    ),
                ),
                (
                    "quote_currency",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rates_as_quote",
                        to="fx.currency",
                    ),
                ),
            ],
            options={
                "verbose_name": "taux de change",
                "verbose_name_plural": "taux de change",
                "ordering": ["-date"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("base_currency", "quote_currency", "date"),
                        name="unique_rate_per_day",
                    )
                ],
            },
        ),
    ]
