# Generated by Django 5.2.17 on 2026-08-31 13:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("budget", "0001_initial"),
        ("imports_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="import_batch",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="transactions",
                to="imports_app.importbatch",
            ),
        ),
        migrations.AddConstraint(
            model_name="category",
            constraint=models.UniqueConstraint(
                fields=("household", "name", "kind"),
                name="unique_category_per_household",
            ),
        ),
        migrations.AddIndex(
            model_name="transaction",
            index=models.Index(
                fields=["household", "date"], name="budget_tran_househo_083753_idx"
            ),
        ),
    ]
