# Generated by Django 5.2.17 on 2026-09-02 10:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_magiclogintoken"),
        ("budget", "0003_alter_financialaccount_owner"),
        ("fx", "0002_seed_currencies"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="RecurringTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "description",
                    models.CharField(max_length=255, verbose_name="description"),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Positif pour une entrée d'argent, négatif pour une sortie.",
                        max_digits=14,
                        verbose_name="montant",
                    ),
                ),
                (
                    "frequency",
                    models.CharField(
                        choices=[
                            ("weekly", "Hebdomadaire"),
                            ("monthly", "Mensuelle"),
                            ("quarterly", "Trimestrielle"),
                            ("yearly", "Annuelle"),
                        ],
                        max_length=10,
                        verbose_name="fréquence",
                    ),
                ),
                (
                    "interval",
                    models.PositiveSmallIntegerField(
                        default=1,
                        help_text="Toutes les N périodes (1 = chaque période).",
                        verbose_name="intervalle",
                    ),
                ),
                ("start_date", models.DateField(verbose_name="première échéance")),
                (
                    "end_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="dernière échéance"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="active")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recurring_transactions",
                        to="budget.financialaccount",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="recurring_transactions",
                        to="budget.category",
                    ),
                ),
                (
                    "currency",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="fx.currency",
                    ),
                ),
                (
                    "household",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="accounts.household",
                    ),
                ),
            ],
            options={
                "verbose_name": "transaction récurrente",
                "verbose_name_plural": "transactions récurrentes",
                "ordering": ["description"],
            },
        ),
        migrations.CreateModel(
            name="BudgetLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "month",
                    models.DateField(
                        help_text="Premier jour du mois budgété.", verbose_name="mois"
                    ),
                ),
                (
                    "planned_amount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Montant attendu, en valeur absolue (600 pour 600 € de courses).",
                        max_digits=14,
                        verbose_name="montant prévu",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="budget_lines",
                        to="budget.category",
                    ),
                ),
                (
                    "household",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="accounts.household",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        help_text="Laisser vide pour un élément commun au foyer.",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "ligne de budget",
                "verbose_name_plural": "lignes de budget",
                "ordering": ["month", "category__name"],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("owner__isnull", False)),
                        fields=("household", "category", "month", "owner"),
                        name="unique_personal_budget_line",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("owner__isnull", True)),
                        fields=("household", "category", "month"),
                        name="unique_joint_budget_line",
                    ),
                ],
            },
        ),
    ]
