# Generated by Django 5.2.17 on 2026-09-02 11:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("budget", "0004_recurringtransaction_budgetline"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="budgetline",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="budget_lines",
                to="budget.category",
                verbose_name="catégorie",
            ),
        ),
        migrations.AlterField(
            model_name="budgetline",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                help_text="Laisser vide pour un élément commun au foyer.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
                verbose_name="propriétaire",
            ),
        ),
        migrations.AlterField(
            model_name="financialaccount",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                help_text="Laisser vide pour un élément commun au foyer.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
                verbose_name="propriétaire",
            ),
        ),
        migrations.AlterField(
            model_name="recurringtransaction",
            name="account",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="recurring_transactions",
                to="budget.financialaccount",
                verbose_name="compte",
            ),
        ),
        migrations.AlterField(
            model_name="recurringtransaction",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="recurring_transactions",
                to="budget.category",
                verbose_name="catégorie",
            ),
        ),
    ]
